/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientmonitoringsystem;

import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.tree.*;

/**
 *
 * @author tinh.pv
 */
public class MainForm extends javax.swing.JFrame {

    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblInfor = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMonitor = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLstClient = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(432, 50));

        lblInfor.setText("IP & Port");
        lblInfor.setMaximumSize(new java.awt.Dimension(100, 16));
        lblInfor.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel2.add(lblInfor);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel2.add(btnStart);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        txtSearch.setText("jTextField1");

        jButton1.setText("jButton1");

        tableMonitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Thời điểm", "Action", "IP Client", "Diễn giải"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableMonitor);

        tableLstClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "IP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableLstClient);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static final int NUM_OF_THREAD = 4;
    public final static int SERVER_PORT = 7000;
    ExecutorService executor = Executors.newFixedThreadPool(NUM_OF_THREAD);
    ServerSocket serverSocket = null;
    
    
    
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        try {
            serverSocket = new ServerSocket(SERVER_PORT);
            lblInfor.setText("Waiting for client connections on: " + serverSocket.getInetAddress().getLocalHost().getHostAddress() + ":" + SERVER_PORT);
            RunThread rt = new RunThread();
            rt.start();
            TableFilter tb = new TableFilter();
            tb.start();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    class RunThread extends Thread {
        //private JTable _table;
        public RunThread() //JTable table
        {
            //this._table = table;
        }

        public void run()
        {
            try
            {
                while (true) {
                    
                    Socket socket = serverSocket.accept();
                    System.out.println("Client accepted: " + socket);
                    WorkWithClient th  = new WorkWithClient(socket);
                    th.start();
                    
                    Thread.sleep(100);
                }
            }
            catch (Exception ex)
            {

            }
        }
    }
    
    class WorkWithClient extends Thread
    {
        private Socket socket;
        //private JTable _table;
        public WorkWithClient(Socket socket) {
            this.socket = socket;
        }
 
        public void run() {
            System.out.println("Processing: " + socket);
            try {
                InputStreamReader inputstreamreader = new    
                InputStreamReader(socket.getInputStream());

                BufferedReader bufferedreader = new  
                BufferedReader(inputstreamreader);

                PrintWriter printwriter = new  
                PrintWriter(socket.getOutputStream(),true);

                String line = "";
                boolean done = false;
                while (((line = bufferedreader.readLine()) != null) &&(!done)){
                    DefaultTableModel model = (DefaultTableModel) tableLstClient.getModel();
                    TableListClient Clientth = new TableListClient(model);
                    int rowCount = model.getRowCount();
                    model.addRow(new Object[]{rowCount + 1, (socket.getInetAddress().getLocalHost().getHostAddress().toString() + ":"+ String.valueOf(socket.getPort())) });
                    Clientth.start();
                    if (line.compareToIgnoreCase("Exit") == 0) done = true;
                }
            } catch (IOException e) {
                System.err.println("Request Processing Error: " + e);
            }
            System.out.println("Complete processing: " + socket);   
        }
    }
    
    class TableListClient extends Thread{
        private final DefaultTableModel _model;
        public TableListClient(DefaultTableModel model)
        {
            this._model = model;
        }
        @Override
        public void run()
        {
            try {
                SwingUtilities.invokeLater(new Runnable() {
                @Override
                    public void run() {
                        _model.fireTableDataChanged();
                    }
                });
                Thread.sleep(1000);
            } catch (Exception e) {
            }
   
        }
    }
    
    class TableFilter extends Thread{
        public TableFilter()
        {
        }
        @Override
        public void run()
        {
            try {
                TableRowSorter<TableModel> sort = new TableRowSorter<>(tableLstClient.getModel());
                tableLstClient.setRowSorter(sort);
                SwingUtilities.invokeLater(new Runnable(){
                    @Override
                    public void run() {
                        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
                        @Override
                            public void insertUpdate(DocumentEvent e) {
                                String str = txtSearch.getText();
                                if (str.trim().length() == 0) {
                                    sort.setRowFilter(null);
                                } else {
                                    sort.setRowFilter(RowFilter.regexFilter("(?i)" + str));
                                }
                            }

                            @Override
                            public void removeUpdate(DocumentEvent e) {
                                String str = txtSearch.getText();
                                if (str.trim().length() == 0) {
                                    sort.setRowFilter(null);
                                } else {
                                    sort.setRowFilter(RowFilter.regexFilter("(?i)" + str));
                                }
                            }

                            @Override
                            public void changedUpdate(DocumentEvent e) {
                                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                            }
                        });
                    }
                });
                
                
            } catch (Exception e) {
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblInfor;
    private javax.swing.JTable tableLstClient;
    private javax.swing.JTable tableMonitor;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
